import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.39.0";
import { zipSync } from "https://esm.sh/fflate@0.8.2";
import { PDFDocument, rgb, StandardFonts } from "https://esm.sh/pdf-lib@1.17.1";

async function generateCoverPage(params: {
  firmName: string;
  firmEmail: string | null;
  claimNumber: string;
  insuredName: string;
  vehicleYear: number | null;
  vehicleMake: string | null;
  vehicleModel: string | null;
  vin: string | null;
  appointmentTime: string | null;
  photoCount: number;
  docNames: string[];
}): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const page = doc.addPage([612, 792]); // Letter size
  const { width, height } = page.getSize();

  const fontBold = await doc.embedFont(StandardFonts.HelveticaBold);
  const fontRegular = await doc.embedFont(StandardFonts.Helvetica);

  const amber = rgb(0.91, 0.58, 0.16);
  const white = rgb(0.91, 0.90, 0.89);
  const dark = rgb(0.055, 0.059, 0.067);

  // Background
  page.drawRectangle({ x: 0, y: 0, width, height, color: dark });

  // Header bar
  page.drawRectangle({ x: 0, y: height - 80, width, height: 80, color: amber });

  // Company name
  page.drawText((params.firmName || 'Independent Appraisal Services').toUpperCase(), {
    x: 40, y: height - 50,
    size: 22, font: fontBold, color: dark
  });

  page.drawText('Independent Appraisal Services', {
    x: 40, y: height - 68,
    size: 10, font: fontRegular, color: dark
  });

  // Title
  page.drawText('CLAIM INSPECTION PACKAGE', {
    x: 40, y: height - 120,
    size: 18, font: fontBold, color: amber
  });

  // Divider
  page.drawLine({
    start: { x: 40, y: height - 135 },
    end: { x: width - 40, y: height - 135 },
    thickness: 1, color: amber, opacity: 0.4
  });

  // Claim details
  const details = [
    ['Claim Number', params.claimNumber],
    ['Insured', params.insuredName || '—'],
    ['Vehicle', [params.vehicleYear, params.vehicleMake, params.vehicleModel].filter(Boolean).join(' ') || '—'],
    ['VIN', params.vin || '—'],
    ['Inspection Date', params.appointmentTime ? new Date(params.appointmentTime).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }) : '—'],
  ];

  let y = height - 165;
  for (const [label, value] of details) {
    page.drawText(label + ':', { x: 40, y, size: 9, font: fontBold, color: amber });
    page.drawText(String(value), { x: 200, y, size: 9, font: fontRegular, color: white });
    y -= 22;
  }

  // Second divider
  page.drawLine({
    start: { x: 40, y: y - 10 },
    end: { x: width - 40, y: y - 10 },
    thickness: 1, color: amber, opacity: 0.4
  });
  y -= 35;

  // Package contents
  page.drawText('PACKAGE CONTENTS', { x: 40, y, size: 12, font: fontBold, color: amber });
  y -= 25;

  page.drawText('Photos:', { x: 40, y, size: 9, font: fontBold, color: amber });
  page.drawText(`${params.photoCount} inspection photos`, { x: 200, y, size: 9, font: fontRegular, color: white });
  y -= 22;

  page.drawText('Documents:', { x: 40, y, size: 9, font: fontBold, color: amber });
  const docList = params.docNames.map(n => n.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase())).join(', ');
  page.drawText(docList || '—', { x: 200, y, size: 9, font: fontRegular, color: white });

  // Footer
  page.drawLine({
    start: { x: 40, y: 80 },
    end: { x: width - 40, y: 80 },
    thickness: 1, color: amber, opacity: 0.4
  });

  page.drawText('Generated by Claim Cipher™', { x: 40, y: 58, size: 8, font: fontRegular, color: amber });
  const footerFirm = params.firmName || 'Independent Appraisal Services';
  page.drawText(params.firmEmail ? `${footerFirm}  |  ${params.firmEmail}` : footerFirm, { x: 40, y: 44, size: 8, font: fontRegular, color: white });

  return doc.save();
}

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { status: 204, headers: corsHeaders });
  }

  try {
    const { claim_id, firm_id } = await req.json();

    if (!claim_id || !firm_id) {
      return new Response(
        JSON.stringify({ error: "claim_id and firm_id are required" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // CD client (all data)
    const cdUrl = Deno.env.get("SUPABASE_URL")!;
    const cdKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const cdSupabase = createClient(cdUrl, cdKey, {
      auth: { autoRefreshToken: false, persistSession: false },
    });

    // Fetch photos, documents, claim info, and vendor info in parallel
    const [photosRes, docsRes, claimRes, vendorRes] = await Promise.all([
      cdSupabase
        .from("claim_photos")
        .select("*")
        .eq("claim_id", claim_id)
        .eq("firm_id", firm_id)
        .order("order_index"),
      cdSupabase
        .from("documents")
        .select("*")
        .eq("claim_id", claim_id)
        .eq("firm_id", firm_id)
        .neq("type", "package"),
      cdSupabase
        .from("claims")
        .select("claim_number")
        .eq("id", claim_id)
        .single(),
      cdSupabase
        .from("vendors")
        .select("name, contact_email")
        .eq("id", firm_id)
        .single(),
    ]);

    const photos = photosRes.data || [];
    const documents = docsRes.data || [];
    const claimNumber = claimRes.data?.claim_number || "unknown";
    const firmName = vendorRes.data?.name || '';
    const firmEmail = vendorRes.data?.contact_email || null;

    console.log(`Packaging claim ${claimNumber}: ${photos.length} photos, ${documents.length} documents`);

    // Generate signed URLs for photos
    const photoUrls: { url: string; name: string }[] = [];
    for (let i = 0; i < photos.length; i++) {
      const photo = photos[i];
      const { data } = await cdSupabase.storage
        .from("claim-photos")
        .createSignedUrl(photo.storage_path, 300);
      if (data?.signedUrl) {
        const idx = String(i + 1).padStart(2, "0");
        const type = photo.photo_type || "photo";
        photoUrls.push({ url: data.signedUrl, name: `${idx}_${type}.jpg` });
      }
    }

    // Generate signed URLs for documents
    const docUrls: { url: string; name: string }[] = [];
    for (const doc of documents) {
      const { data } = await cdSupabase.storage
        .from("documents")
        .createSignedUrl(doc.storage_path, 300);
      if (data?.signedUrl) {
        docUrls.push({ url: data.signedUrl, name: doc.file_name || `document_${doc.id}` });
      }
    }

    // Fetch all photos in parallel — collect results
    const photoResults = await Promise.all(photoUrls.map(async (item) => {
      try {
        const resp = await fetch(item.url);
        if (resp.ok) {
          const bytes = new Uint8Array(await resp.arrayBuffer());
          if (bytes.length > 0) {
            console.log(`Fetched photo: ${item.name} (${bytes.length} bytes)`);
            return { name: `photos/${item.name}`, bytes };
          }
        } else {
          console.error(`Failed photo ${item.name}: ${resp.status}`);
        }
      } catch (err) {
        console.error(`Error photo ${item.name}:`, err);
      }
      return null;
    }));

    // Fetch all documents in parallel — collect results
    const docResults = await Promise.all(docUrls.map(async (item) => {
      try {
        const resp = await fetch(item.url);
        if (resp.ok) {
          const bytes = new Uint8Array(await resp.arrayBuffer());
          if (bytes.length > 0) {
            console.log(`Fetched document: ${item.name} (${bytes.length} bytes)`);
            return { name: `documents/${item.name}`, bytes };
          }
        } else {
          console.error(`Failed doc ${item.name}: ${resp.status}`);
        }
      } catch (err) {
        console.error(`Error doc ${item.name}:`, err);
      }
      return null;
    }));

    // Fetch additional claim details for cover page
    const { data: claimDetails } = await cdSupabase
      .from('claims')
      .select('customer_name, vehicle_year, vehicle_make, vehicle_model, vin, scheduled_at, appointment_start, completed_at')
      .eq('id', claim_id)
      .single();

    // Generate cover page
    const coverPageBytes = await generateCoverPage({
      firmName,
      firmEmail,
      claimNumber,
      insuredName: claimDetails?.customer_name ?? null,
      vehicleYear: claimDetails?.vehicle_year ?? null,
      vehicleMake: claimDetails?.vehicle_make ?? null,
      vehicleModel: claimDetails?.vehicle_model ?? null,
      vin: claimDetails?.vin ?? null,
      appointmentTime: claimDetails?.scheduled_at
        || claimDetails?.appointment_start
        || claimDetails?.completed_at
        || null,
      photoCount: photoResults.filter(r => r !== null).length,
      docNames: documents.map((d: any) => d.type),
    });

    // Build zip synchronously after all fetches complete
    const allResults = [...photoResults, ...docResults].filter(r => r !== null) as { name: string; bytes: Uint8Array }[];
    console.log(`Total files to zip: ${allResults.length}`);

    const files: Record<string, Uint8Array> = {};
    for (const result of allResults) {
      files[result.name] = result.bytes;
    }

    // Add cover page to zip at top level
    files['00_CLAIM_PACKAGE_COVER.pdf'] = coverPageBytes;
    console.log(`Cover page generated: ${coverPageBytes.length} bytes`);

    console.log(`Files in zip object: ${Object.keys(files).length}`);
    const zipBlob = zipSync(files, { level: 1 });
    console.log(`Zip generated: ${zipBlob.length} bytes`);

    // Upload zip to packages bucket
    const storagePath = `firm/${firm_id}/claim/${claim_id}/claim-package.zip`;
    const { error: uploadError } = await cdSupabase.storage
      .from("packages")
      .upload(storagePath, zipBlob, { contentType: "application/zip", upsert: true });

    if (uploadError) {
      throw new Error(`Failed to upload package: ${uploadError.message}`);
    }

    // Insert document record in CD
    await cdSupabase.from("documents").upsert({
      claim_id,
      firm_id,
      type: "package",
      storage_path: storagePath,
      file_name: "claim-package.zip",
    }, { onConflict: "claim_id,firm_id,type" });

    // Generate signed URL for download (7 days)
    const { data: signedData, error: signError } = await cdSupabase.storage
      .from("packages")
      .createSignedUrl(storagePath, 604800);

    if (signError || !signedData?.signedUrl) {
      throw new Error("Failed to generate download URL");
    }

    return new Response(
      JSON.stringify({
        signed_url: signedData.signedUrl,
        file_name: "claim-package.zip",
        expires_in: 604800,
      }),
      { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (err) {
    console.error("Package generation error:", err);
    return new Response(
      JSON.stringify({ error: err.message }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
